CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    password BYTEA NOT NULL,
    email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS households (
    HSHD_NUM TEXT PRIMARY KEY,
    L TEXT NOT NULL,
    AGE_RANGE TEXT,
    MARITAL TEXT,
    INCOME_RANGE TEXT,
    HOMEOWNER TEXT,
    HSHD_COMPOSITION TEXT,
    HH_SIZE TEXT,
    CHILDREN TEXT
);

CREATE TABLE IF NOT EXISTS products (
    PRODUCT_NUM TEXT PRIMARY KEY,
    DEPARTMENT TEXT NOT NULL,
    COMMODITY TEXT NOT NULL,
    BRAND_TY TEXT NOT NULL,
    NATURAL_ORGANIC_FLAG TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    BASKET_NUMBER TEXT NOT NULL,
    HSHD_NUM TEXT NOT NULL,
    PURCHASE DATE NOT NULL,
    PRODUCT_NUM TEXT NOT NULL,
    SPEND REAL NOT NULL,
    UNITS INTEGER NOT NULL,
    STORE_R TEXT NOT NULL,
    WEEK_NUM INTEGER NOT NULL,
    YEAR INTEGER NOT NULL,
    FOREIGN KEY (HSHD_NUM) REFERENCES households (HSHD_NUM),
    FOREIGN KEY (PRODUCT_NUM) REFERENCES products (PRODUCT_NUM)
);
